version : "3.4"

services:
    postgres:
      image: postgres:latest
      container_name: postgresExample
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: sccs
      ports:
        - 5432:5432
      volumes:
        - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db: 